
# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "master"
  # version = "=v0.0.5"

[[constraint]]
  name = "github.com/openshift/elasticsearch-operator"
  branch = "master"

[[constraint]]
  name = "github.com/openshift/api"
  #version = "3.11.0"
  branch = "master"
