- op: replace
  path: /spec/validation/openAPIV3Schema/properties/metadata
  value:
    type: object
    properties:
      name:
        type: string
        enum:
        - "instance"
- op: replace
  path: /spec/validation/openAPIV3Schema/properties/status
  value:
    type: object
