---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: watch-cluster-logging
  namespace: openshift-logging
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
roleRef:
  kind: Role
  name: watch-cluster-logging
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-logging-operator-rolebinding
  namespace: openshift-logging
subjects:
- kind: ServiceAccount
  name: cluster-logging-operator
  namespace: openshift-logging
roleRef:
  kind: Role
  name: cluster-logging-operator
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-logging-operator-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: cluster-logging-operator
  namespace: openshift-logging
roleRef:
  kind: ClusterRole
  name: cluster-logging-operator-cluster
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-logging-operator-cluster-reader-binding
subjects:
- kind: ServiceAccount
  name: cluster-logging-operator
  namespace: openshift-logging
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io
