---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-logging-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: cluster-logging-operator
roleRef:
  kind: Role
  name: cluster-logging-operator
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-logging-operator-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: cluster-logging-operator
  namespace: cluster-logging
roleRef:
  kind: ClusterRole
  name: cluster-logging-operator-cluster
  apiGroup: rbac.authorization.k8s.io
