# permissions for end users to view clusterloggings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterlogging-viewer-role
rules:
- apiGroups:
  - logging.openshift.io
  resources:
  - clusterloggings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.openshift.io
  resources:
  - clusterloggings/status
  verbs:
  - get
