# permissions for end users to view clusterlogforwarders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterlogforwarder-viewer-role
rules:
- apiGroups:
  - logging.openshift.io
  resources:
  - clusterlogforwarders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - logging.openshift.io
  resources:
  - clusterlogforwarders/status
  verbs:
  - get
