# permissions for end users to edit clusterloggings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterlogging-editor-role
rules:
- apiGroups:
  - logging.openshift.io
  resources:
  - clusterloggings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.openshift.io
  resources:
  - clusterloggings/status
  verbs:
  - get
