# permissions for end users to edit clusterlogforwarders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterlogforwarder-editor-role
rules:
- apiGroups:
  - logging.openshift.io
  resources:
  - clusterlogforwarders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.openshift.io
  resources:
  - clusterlogforwarders/status
  verbs:
  - get
