kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-deployer
subjects:
  - kind: ServiceAccount
    name: cluster-logging-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logging-deployer
