apiVersion: "logging.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    logging.openshift.io/opentelemetry: enabled
spec:
  pipelines:
  - inputRefs:
    - application
    name: application-logs
    outputRefs:
    - default