apiVersion: logging.openshift.io/v1alpha1
kind: LogForwarding
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
  - endpoint: tcp://fluent-receiver.openshift-logging.svc:24224
    name: remote
    type: forward
  pipelines:
  - inputSource: logs.audit
    name: forward-pipeline
    outputRefs:
    - remote
