apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-logging-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-logging-operator
  template:
    metadata:
      labels:
        name: cluster-logging-operator
    spec:
      serviceAccountName: cluster-logging-operator
      containers:
        - name: cluster-logging-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - cluster-logging-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cluster-logging-operator"
